version: 2
jobs:
  test-3.6: &test-template
    docker:
      - image: python:3.6-stretch
    steps:
      - run:
          name: install Java
          command: apt-get update && apt-get install -y openjdk-8-jre
      - checkout
      - run:
          name: install
          command: pip install '.[test]'
      - run:
          name: generate html
          working_directory: test/example_site
          command: pelican content -s pelicanconf.py
      - run:
          name: validate html
          command: html5validator --root test/example_site/output
  test-3.5:
    <<: *test-template
    docker:
      - image: python:3.5-stretch
  test-2.7:
    <<: *test-template
    docker:
      - image: python:2.7-stretch
workflows:
  version: 2
  build_and_test:
    jobs:
      - test-2.7
      - test-3.6
