version: 2
jobs:
  test-3.6:
    docker:
      - image: python:3.6
    steps:
      - checkout
      - run:
          name: install
          command: pip install '.[test]'
      - run:
          name: install Java
          command: apt-get install -y default-jdk
      - run:
          name: generate html
          working_directory: test/example_site
          command: pelican content -s pelicanconf.py
      - run:
          name: validate html
          command: html5validator --root test/example_site/output
  test-2.7:
    docker:
      - image: python:2.7
    steps:
      - checkout
      - run:
          name: install
          command: pip install '.[test]'
      - run:
          name: generate html
          working_directory: test/example_site
          command: pelican content -s pelicanconf.py
      - run:
          name: validate html
          command: html5validator --root test/example_site/output
workflows:
  version: 2
  build_and_test:
    jobs:
      - test-2.7
      - test-3.6
