version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.1
    steps:
      - checkout
      - run:
          name: generate html
          working_directory: test/example_site
          command: pelican content -s pelicanconf.py
  test:
    docker:
      - image: circleci/python:3.6.1
    steps:
      - checkout
      - run:
          name: validate html
          command: html5validator --root test/example_site/output
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
